2025-03-08 16:08:21,188 - 26 - root - INFO - Entered the data ingestion method or compponent
2025-03-08 16:08:21,194 - 32 - root - INFO - reading the dataset as dataframe
2025-03-08 16:08:21,194 - 57 - root - ERROR - Error reading dataset
Traceback (most recent call last):
  File "c:\Users\Rotim\OneDrive\Documents\Data_Science_Projects\Student_ML_Project\src\components\data_ingestion.py", line 36, in initiate_data_ingestion
    print( f"The directory exists {artifacts}")
NameError: name 'artifacts' is not defined
